config/routes.rb
Rails.application.routes.draw do

    get "/about" => "public/homes#about"

  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
  }

  namespace :admin do
    get 'top' => 'homes#top', as: 'top'
    get 'search' => 'homes#search', as: 'search'
    get 'users/:user_id/reviews' => 'reviews#index', as: 'user_reviews'
    resources :users, only: [:index, :show, :edit, :update]
    resources :reviews, only: [:index, :show, :update, :destroy] do
      resources :review_comments, only: [:destroy]
    end
    resources :genres, only: [:index, :create, :edit, :update]
  end


  devise_for :users, controllers: {
    sessions: 'public/sessions',
    registrations: 'public/registrations',
  }

  devise_scope :user do
    post 'user/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  scope module: :public do
    root 'homes#top'

    get 'users/mypage' => 'users#show', as: 'mypage'
    # users/editのようにするとdeviseのルーティングとかぶってしまうためinformationを付け加えている。
    get 'users/information/edit' => 'users#edit', as: 'edit_information'
    patch 'users/information' => 'users#update', as: 'update_information'
    get 'users/unsubscribe' => 'users#unsubscribe', as: 'confirm_unsubscribe'
    put 'users/information' => 'users#update'
    patch 'users/withdraw' => 'users#withdraw', as: 'withdraw_user'
    get 'tagsearches/search', to: 'tagsearches#search'

    resources :reviews, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      resources :review_comments, only: [:create, :destroy]
    end
  end
  
end

app/models/review_comment.rb
class ReviewComment < ApplicationRecord
  belongs_to :user
  belongs_to :review
  validates :comment, presence: true, length: { maximum: 100 }
end

app/controllers/admin/review_comments_controller.rb
class Admin::ReviewCommentsController < ApplicationController

  def destroy
    @comment = ReviewComment.find(params[:id])
    @comment.destroy
    @review = Review.find(params[:review_id])
  end
end

app/helpers/admin/review_comments_helper.rb
module Admin::ReviewCommentsHelper
end

app/views/admin/review_comments/_counter.html.erb
<h5>コメント件数：<%= review.review_comments.count %></h5>

app/views/admin/review_comments/_index.html.erb
<% review.review_comments.each do |review_comment| %>
<div class="review-comment">
  <p><%= image_tag review_comment.user.get_profile_image, class:"mt-3 rounded-circle img-fluid" %></p>
  <p><strong><%= review_comment.user.name %></strong></p>
  <p><%= review_comment.created_at.strftime('%Y/%m/%d') %></p>
  <p><%= review_comment.comment %></p>

  <% if current_admin && current_admin.admin? %>
    <%= link_to "削除", admin_review_review_comment_path(review_comment.review, review_comment), method: :delete, data: { confirm: "本当に削除しますか？" }, remote:true, data: { "turbolinks" => false }, class: "btn btn-danger" %>
  <% end %>
</div>
<% end %>

app/views/admin/review_comments/destroy.js.erb
$('#comment_counter').html('<%= j(render partial: "admin/review_comments/counter", locals: { review: @review }) %>');
$('#comment_index').html('<%= j(render partial: "admin/review_comments/index", locals: { review: @review }) %>');