config/routes.rb
Rails.application.routes.draw do

    get "/about" => "public/homes#about"

  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
  }

  namespace :admin do
    get 'top' => 'homes#top', as: 'top'
    get 'search' => 'homes#search', as: 'search'
    get 'users/:user_id/reviews' => 'reviews#index', as: 'user_reviews'
    resources :users, only: [:index, :show, :edit, :update]
    resources :reviews, only: [:index, :show, :update, :destroy] do
      resources :review_comments, only: [:destroy]
    end
    resources :genres, only: [:index, :create, :edit, :update]
  end


  devise_for :users, controllers: {
    sessions: 'public/sessions',
    registrations: 'public/registrations',
  }

  devise_scope :user do
    post 'user/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  scope module: :public do
    root 'homes#top'

    get 'users/mypage' => 'users#show', as: 'mypage'
    # users/editのようにするとdeviseのルーティングとかぶってしまうためinformationを付け加えている。
    get 'users/information/edit' => 'users#edit', as: 'edit_information'
    patch 'users/information' => 'users#update', as: 'update_information'
    get 'users/unsubscribe' => 'users#unsubscribe', as: 'confirm_unsubscribe'
    put 'users/information' => 'users#update'
    patch 'users/withdraw' => 'users#withdraw', as: 'withdraw_user'
    get 'tagsearches/search', to: 'tagsearches#search'

    resources :reviews, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      resources :review_comments, only: [:create, :destroy]
    end
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reviews, dependent: :destroy
  has_many :review_comments, dependent: :destroy
  has_one_attached :profile_image
  
  validates :name, presence: true
  validates :email, presence: true

  def get_profile_image
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [100, 100]).processed
  end

  def active_for_authentication?
    super && (is_active == true)
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "Guestuser"
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @users = User.page(params[:page]).per(10)
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "変更が完了しました"
      redirect_to admin_user_path(@user)
    else
      render :edit
    end
  end

  def user_params
    params.require(:user).permit(:name, :email, :profile_image, :is_active)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="container">
  <div class="row no-gutters">
    <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto text-center shadow-lg rounded px-0 my-5">
      <h5 class="text-dark bg-light py-4 mb-0">プロフィール編集</h5>

      <div class="form-body p-4">
        <% if @user.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@user.errors.count, "件") %> のエラーが発生しました：</h2>
            <ul>
              <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <%= form_with model: @user, url: admin_user_path(@user), method: :patch do |f| %>
          <div class="form-group mb-3 mt-4">
            <%= f.label :profile_image, "プロフィール画像", class: "form-label" %>
            <%= f.file_field :profile_image, class: "form-control-file" %>
          </div>

          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text" aria-hidden="true"><i class="fas fa-user"></i></span>
            </div>
            <%= f.text_field :name, autofocus: true, class:"form-control", id:"inputName", placeholder:"ユーザー名"%>
          </div>

          <div class="input-group my-3">
            <div class="input-group-prepend">
              <span class="input-group-text" aria-hidden="true"><i class="fas fa-envelope"></i></span>
            </div>
            <%= f.email_field :email, class:"form-control", id:"inputEmail", placeholder:"メールアドレス"%>
          </div>

          <div>会員ステータス</div>
            <div class="form-group">
            <div class="form-check form-check-inline">
              <%= f.radio_button :is_active, true, class: 'form-check-input', id: 'is_active_true' %>
              <%= f.label :is_active_true, "有効", class: 'form-check-label' %>
            </div>

            <div class="form-check form-check-inline">
              <%= f.radio_button :is_active, false, class: 'form-check-input', id: 'is_active_false' %>
              <%= f.label :is_active_false, "退会", class: 'form-check-label' %>
            </div>
          </div>

          <%= f.submit "変更を保存", class:"btn btn-lg btn-block btn-success mt-5" %>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="container">
  <div class="row d-flex justify-content-center">
    <h5 class="p-3 my-3">会員一覧</h5>
  </div>

  <div class="row">
    <table class="table">
      <thead>
        <tr>
          <th>会員ID</th>
          <th>ユーザー名</th>
          <th>メールアドレス</th>
          <th>会員ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>

        <tr>
          <td><%= user.id %></td>

          <td><%= link_to user.name, admin_user_path(user) %></td>

          <td><%= user.email %></td>

          <td>
            <% if user.is_active %>
              <a>有効</a>
            <% else %>
              <a>退会</a>
            <% end %>
          </td>
        </tr>

        <% end %>
      </tbody>
    </table>
  </div>

  <div class="row">
    <div class="col-12 d-flex justify-content-center">
      <%= paginate @users %>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="profile-container w-75 d-flex mx-auto justify-content-around align-items-center border-bottom py-5">
  <%= image_tag @user.get_profile_image, class:"rounded-circle";  %>
  <h5 class="profile-name display-4"><%= @user.name %></h5>
  <div class="mt-auto">
    <p><%= link_to "プロフィール編集", edit_admin_user_path(@user), class:"text-dark" %></p>
  </div>
</div>