config/routes.rb
Rails.application.routes.draw do

    get "/about" => "public/homes#about"

  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
  }

  namespace :admin do
    get 'top' => 'homes#top', as: 'top'
    get 'search' => 'homes#search', as: 'search'
    get 'users/:user_id/reviews' => 'reviews#index', as: 'user_reviews'
    resources :users, only: [:index, :show, :edit, :update]
    resources :reviews, only: [:index, :show, :update, :destroy] do
      resources :review_comments, only: [:destroy]
    end
    resources :genres, only: [:index, :create, :edit, :update]
  end


  devise_for :users, controllers: {
    sessions: 'public/sessions',
    registrations: 'public/registrations',
  }

  devise_scope :user do
    post 'user/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  scope module: :public do
    root 'homes#top'

    get 'users/mypage' => 'users#show', as: 'mypage'
    # users/editのようにするとdeviseのルーティングとかぶってしまうためinformationを付け加えている。
    get 'users/information/edit' => 'users#edit', as: 'edit_information'
    patch 'users/information' => 'users#update', as: 'update_information'
    get 'users/unsubscribe' => 'users#unsubscribe', as: 'confirm_unsubscribe'
    put 'users/information' => 'users#update'
    patch 'users/withdraw' => 'users#withdraw', as: 'withdraw_user'
    get 'tagsearches/search', to: 'tagsearches#search'

    resources :reviews, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      resources :review_comments, only: [:create, :destroy]
    end
  end
  
end

app/views/layouts/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ラーメン探訪記</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>



    <script src="https://kit.fontawesome.com/c579d0a523.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-warning">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand ml-auto" href="/">
          <%= image_tag "Logo.jpg", width: '100px', class: "img-fluid" %>
        </a>
        <div class="collapse navbar-collapse justify-content-center" id="navbarSupportedContent">
          <ul class="navbar-nav">
            <% if admin_signed_in? %>
              <li class='nav-item'>
                <%= link_to 'ラーメン一覧', admin_reviews_path, class: 'btn btn-outline-dark mr-1' %>
              </li>
              <li class='nav-item'>
                <%= link_to '会員一覧', admin_users_path, class: 'btn btn-outline-dark mr-1' %>
              </li>
              <li class='nav-item'>
                <%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class: 'btn btn-outline-dark' %>
              </li>

            <% elsif user_signed_in? %>
              <li class="text-secondary mr-5 mt-2">ようこそ、<%= current_user.name %>さん！</li>
              <li class="nav-item">
                <%= link_to 'マイページ', mypage_path, class: 'btn btn-outline-dark mr-1' %>
              </li>
              <li class="nav-item">
                <%= link_to '投稿', new_review_path, class: "btn btn-outline-dark mr-1" %>
              </li>
              <li class="nav-item">
                <%= link_to 'ラーメン一覧', reviews_path, class: "btn btn-outline-dark mr-1" %>
              </li>
              <li class="nav-item">
                <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "btn btn-outline-dark mr-1" %>
              </li>

              <%= render 'public/tagsearches/tagsearch' %>

            <% else %>
              <li class="nav-item">
                <%= link_to 'ログイン', new_user_session_path, class: "btn btn-outline-dark mr-1" %>
              </li>

              <li class="nav-item">
                <%= link_to '新規登録', new_user_registration_path, class: "btn btn-outline-dark mr-1" %>
              </li>

              <li class="nav-item">
                <%= link_to 'ラーメン一覧', reviews_path, class: "btn btn-outline-dark mr-1" %>
              </li>

              <li class="nav-item">
                <%= link_to 'About', about_path, class: "btn btn-outline-dark mr-1" %>
              </li>

              <li class="nav-item">
                <%= link_to 'ゲストログイン', user_guest_sign_in_path, method: :post, class: "btn btn-outline-dark" %>
              </li>
            <% end %>
          </ul>
        </div>
      </nav>
    </header>
  <main>
    <% if flash[:notice] %>
      <div class="flash-notice"><%= flash[:notice] %></div>
    <% end %>

    <%= yield %>
  </main>
    <footer class="fixed-bottom text-center bg-warning pt-4">
  <div class="container">
    <p style="color: #aaa;">&copy; ラーメン探訪記</p>
  </div>
</footer>
  </body>
</html>